In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup as bs

In [2]:
URL = "https://www.amazon.in/gp/new-releases/electronics/1805560031?ref_=Oct_d_onr_S&pd_rd_w=u4Fyy&content-id=amzn1.sym.6994f97b-af7d-4405-a303-8aac5f8b11eb&pf_rd_p=6994f97b-af7d-4405-a303-8aac5f8b11eb&pf_rd_r=1V7GWQEF03QKS1YZDHEY&pd_rd_wg=kGpon&pd_rd_r=37493293-85df-47ad-b652-4a4b46522957"
URL

'https://www.amazon.in/gp/new-releases/electronics/1805560031?ref_=Oct_d_onr_S&pd_rd_w=u4Fyy&content-id=amzn1.sym.6994f97b-af7d-4405-a303-8aac5f8b11eb&pf_rd_p=6994f97b-af7d-4405-a303-8aac5f8b11eb&pf_rd_r=1V7GWQEF03QKS1YZDHEY&pd_rd_wg=kGpon&pd_rd_r=37493293-85df-47ad-b652-4a4b46522957'

In [3]:
response=requests.get(URL)

In [4]:
Soup=bs(response.text)
print(bs.prettify(Soup))

<!DOCTYPE html>
<html class="a-no-js" data-19ax5a9jf="dingo" lang="en-in">
 <!-- sp:feature:head-start -->
 <head>
  <script>
   var aPageStart = (new Date()).getTime();
  </script>
  <meta charset="utf-8"/>
  <!-- sp:end-feature:head-start -->
  <!-- sp:feature:csm:head-open-part1 -->
  <!-- sp:end-feature:csm:head-open-part1 -->
  <!-- sp:feature:cs-optimization -->
  <meta content="on" http-equiv="x-dns-prefetch-control"/>
  <link href="https://images-eu.ssl-images-amazon.com" rel="dns-prefetch"/>
  <link href="https://m.media-amazon.com" rel="dns-prefetch"/>
  <link href="https://completion.amazon.com" rel="dns-prefetch"/>
  <!-- sp:end-feature:cs-optimization -->
  <!-- sp:feature:csm:head-open-part2 -->
  <!-- sp:end-feature:csm:head-open-part2 -->
  <!-- sp:feature:aui-assets -->
  <link href="https://m.media-amazon.com/images/I/21tNz3PlzXL._RC|51MqAENQaOL.css_.css?AUIClients/AmazonUI" rel="stylesheet">
   <link href="https://m.media-amazon.com/images/I/11Q3J0BXRuL._RC|01ZTHTZObnL.css,41CH6lOLkAL.css,31eW3MUh82L.css,21+Rc0NyPgL.css,01xH+fhFIJL.css,01ik5s7rovL.css,413Vvv3GONL.css,11TIuySqr6L.css,01Rw4F+QU6L.css,11eVyFfmeiL.css,01LmAy9LJTL.css,01IdKcBuAdL.css,01iHqjS7YfL.css,01bwGDJt6oL.css,016EnqvinxL.css,21ft1mghORL.css,01MGI4xLlLL.css,51uKJPgayNL.css,01Hp8zG27eL.css,01XPHJk60-L.css,11tzaLb9IoL.css,01GAxF7K5tL.css,01ZM-s8Z3xL.css,21q2yoLjc-L.css,01aPy8nLK4L.css,21POIeN-EdL.css,11v6F1I-jZL.css,31semobHkIL.css,11+WPnl5uwL.css,31MA1k03oQL.css,11PDZ29p-PL.css,11EEDu-xalL.css,11qIGWAGl5L.css,11sUwulETuL.css,1102TRb3mML.css,01xFKTPySiL.css,218wJxvrDkL.css,21BftfxKE2L.css,01iKUrBgtPL.css,21EMKEfpuPL.css,11eYW22Jy7L.css,119tiEPD7pL.css,11sA4XQpKNL.css,01890+Vwk8L.css,01+fnLEdpwL.css,01qiwJ7qDfL.css,21AS3Iv3HQL.css,016mfgi+D2L.css,01EBrdNjxaL.css,21yf436RgrL.css,21L-cyBBRTL.css,013-xYw+SRL.css_.css?AUIClients/AmazonUI#not-trident" rel="stylesheet">
    <script>
     (function(b,a,c,d){if((b=b.AmazonUIPageJS||b.P)&&b.when&&b.register){c=[];for(a=a.currentScript;a;a=a.parentElement)a.id&&c.push(a.id);return b.log("A copy of P has already been loaded on this page.","FATAL",c.join(" "))}})(window,document,Date);(function(a,b,c,d){"use strict";a._pSetI=function(){return null}})(window,document,Date);(function(c,e,I,B){"use strict";c._pd=function(){var a,u;return function(C,f,h,k,b,D,v,E,F){function w(d){try{return d()}catch(J){return!1}}function l(){if(m){var d={w:c.innerWidth||b.clientWidth,h:c.innerHeight||b.clientHeight};5<Math.abs(d.w-q.w)||50<d.h-q.h?(q=d,n=4,(d=a.mobile||a.tablet?450<d.w&&d.w>d.h:1250<=d.w)?k(b,"a-ws"):b.className=v(b,"a-ws")):0<n&&(n--,x=setTimeout(l,16))}}function G(d){(m=d===B?!m:!!d)&&l()}function H(){return m}if(!u){u=!0;var r=function(){var d=["O","ms","Moz","Webkit"],
c=e.createElement("div");return{testGradients:function(){return!0},test:function(a){var b=a.charAt(0).toUpperCase()+a.substr(1);a=(d.join(b+" ")+b+" "+a).split(" ");for(b=a.length;b--;)if(""===c.style[a[b]])return!0;return!1},testTransform3d:function(){return!0}}}(),y=b.className,z=/(^| )a-mobile( |$)/.test(y),A=/(^| )a-tablet( |$)/.test(y);a={audio:function(){return!!e.createElement("audio").canPlayType},video:function(){return!!e.createElement("video").canPlayType},canvas:function(){return!!e.createElement("canvas").getContext},
svg:function(){return!!e.createElementNS&&!!e.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect},offline:function(){return navigator.hasOwnProperty&&navigator.hasOwnProperty("onLine")&&navigator.onLine},dragDrop:function(){return"draggable"in e.createElement("span")},geolocation:function(){return!!navigator.geolocation},history:function(){return!(!c.history||!c.history.pushState)},webworker:function(){return!!c.Worker},autofocus:function(){return"autofocus"in e.createElement("input")},
inputPlaceholder:function(){return"placeholder"in e.createElement("input")},textareaPlaceholder:function(){return"placeholder"in e.createElement("textarea")},localStorage:function(){return"localStorage"in c&&null!==c.localStorage},orientation:function(){return"orientation"in c},touch:function(){return"ontouchend"in e},gradients:function(){return r.testGradients()},hires:function(){var a=c.devicePixelRatio&&1.5<=c.devicePixelRatio||c.matchMedia&&c.matchMedia("(min-resolution:144dpi)").matches;E("hiRes"+
(z?"Mobile":A?"Tablet":"Desktop"),a?1:0);return a},transform3d:function(){return r.testTransform3d()},touchScrolling:function(){return f(/Windowshop|android|OS ([5-9]|[1-9][0-9]+)(_[0-9]{1,2})+ like Mac OS X|SOFTWARE=([5-9]|[1-9][0-9]+)(.[0-9]{1,2})+.*DEVICE=iPhone|Chrome|Silk|Firefox|Trident.+?; Touch/i)},ios:function(){return f(/OS [1-9][0-9]*(_[0-9]*)+ like Mac OS X/i)&&!f(/trident|Edge/i)},android:function(){return f(/android.([1-9]|[L-Z])/i)&&!f(/trident|Edge/i)},mobile:function(){return z},
tablet:function(){return A},rtl:function(){return"rtl"===b.dir}};for(var g in a)a.hasOwnProperty(g)&&(a[g]=w(a[g]));for(var t="textShadow textStroke boxShadow borderRadius borderImage opacity transform transition".split(" "),p=0;p<t.length;p++)a[t[p]]=w(function(){return r.test(t[p])});var m=!0,x=0,q={w:0,h:0},n=4;l();h(c,"resize",function(){clearTimeout(x);n=4;l()});b.className=v(b,"a-no-js");k(b,"a-js");!f(/OS [1-8](_[0-9]*)+ like Mac OS X/i)||c.navigator.standalone||f(/safari/i)||k(b,"a-ember");
h=[];for(g in a)a.hasOwnProperty(g)&&a[g]&&h.push("a-"+g.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()}));k(b,h.join(" "));b.setAttribute("data-aui-build-date",F);C.register("p-detect",function(){return{capabilities:a,localStorage:a.localStorage&&D,toggleResponsiveGrid:G,responsiveGridEnabled:H}});return a||{}}}}()})(window,document,Date);(function(g,h,C,D){function K(a){l&&l.tag&&l.tag(p(":","aui",a))}function q(a,b){l&&l.count&&l.count("aui:"+a,0===b?0:b||(l.count("aui:"+a)||0)+1)}function L(a){try{return a.test(navigator.userAgent)}catch(b){return!1}}function x(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function p(a,b,c,f){b=b&&c?b+a+c:b||c;return f?p(a,b,f):b}function y(a,b,c){try{Object.defineProperty(a,b,{value:c,writable:!1})}catch(f){a[b]=c}return c}function M(a,b){a.className=
N(a,b)+" "+b}function N(a,b){return(" "+a.className+" ").split(" "+b+" ").join(" ").replace(/^ | $/g,"")}function aa(a,b,c){var f=c=a.length,e=function(){f--||(E.push(b),F||(m?m.set(z):setTimeout(z,0),F=!0))};for(e();c--;)O[a[c]]?e():(u[a[c]]=u[a[c]]||[]).push(e)}function ba(a,b,c,f,e){var d=h.createElement(a?"script":"link");x(d,"error",f);e&&x(d,"load",e);a?(d.type="text/javascript",d.async=!0,c&&/AUIClients|images[/]I/.test(b)&&d.setAttribute("crossorigin","anonymous"),d.src=b):(d.rel="stylesheet",
d.href=b);h.getElementsByTagName("head")[0].appendChild(d)}function P(a,b){return function(c,f){function e(){ba(b,c,d,function(b){G?q("resource_unload"):d?(d=!1,q("resource_retry"),e()):(q("resource_error"),a.log("Asset failed to load: "+c));b&&b.stopPropagation?b.stopPropagation():g.event&&(g.event.cancelBubble=!0)},f)}if(Q[c])return!1;Q[c]=!0;q("resource_count");var d=!0;return!e()}}function ca(a,b,c){for(var f={name:a,guard:function(c){return b.guardFatal(a,c)},guardTime:function(a){return b.guardTime(a)},
logError:function(c,d,e){b.logError(c,d,e,a)}},e=[],d=0;d<c.length;d++)A.hasOwnProperty(c[d])&&(e[d]=H.hasOwnProperty(c[d])?H[c[d]](A[c[d]],f):A[c[d]]);return e}function v(a,b,c,f,e){return function(d,k){function n(){var a=null;f?a=k:"function"===typeof k&&(q.start=r(),a=k.apply(g,ca(d,h,l)),q.end=r());if(b){A[d]=a;a=d;for(O[a]=!0;(u[a]||[]).length;)u[a].shift()();delete u[a]}q.done=!0}var h=e||this;"function"===typeof d&&(k=d,d=D);b&&(d=d?d.replace(R,""):"__NONAME__",I.hasOwnProperty(d)&&h.error(p(", reregistered by ",
p(" by ",d+" already registered",I[d]),h.attribution),d),I[d]=h.attribution);for(var l=[],m=0;m<a.length;m++)l[m]=a[m].replace(R,"");var q=w[d||"anon"+ ++da]={depend:l,registered:r(),namespace:h.namespace};d&&ea.hasOwnProperty(d);c?n():aa(l,h.guardFatal(d,n),d);return{decorate:function(a){H[d]=h.guardFatal(d,a)}}}}function S(a){return function(){var b=Array.prototype.slice.call(arguments);return{execute:v(b,!1,a,!1,this),register:v(b,!0,a,!1,this)}}}function J(a,b){return function(c,f){f||(f=c,c=
D);var e=this.attribution;return function(){n.push(b||{attribution:e,name:c,logLevel:a});var d=f.apply(this,arguments);n.pop();return d}}}function B(a,b){this.load={js:P(this,!0),css:P(this)};y(this,"namespace",b);y(this,"attribution",a)}function T(){h.body?k.trigger("a-bodyBegin"):setTimeout(T,20)}"use strict";var t=C.now=C.now||function(){return+new C},r=function(a){return a&&a.now?a.now.bind(a):t}(g.performance),fa=r(),ea={},l=g.ue;K();K("aui_build_date:3.25.5-2025-08-15");var U={getItem:function(a){try{return g.localStorage.getItem(a)}catch(b){}},
setItem:function(a,b){try{return g.localStorage.setItem(a,b)}catch(c){}}},m=g._pSetI(),E=[],ha=[],F=!1,ia=navigator.scheduling&&"function"===typeof navigator.scheduling.isInputPending;var z=function(){for(var a=m?m.set(z):setTimeout(z,0),b=t();ha.length||E.length;)if(E.shift()(),m&&ia){if(150<t()-b&&!navigator.scheduling.isInputPending()||50<t()-b&&navigator.scheduling.isInputPending())return}else if(50<t()-b)return;m?m.clear(a):clearTimeout(a);F=!1};var O={},u={},Q={},G=!1;x(g,"beforeunload",function(){G=
!0;setTimeout(function(){G=!1},1E4)});var R=/^prv:/,I={},A={},H={},w={},da=0,ja=String.fromCharCode(92),n=[],V=!0,W=g.onerror;g.onerror=function(a,b,c,f,e){e&&"object"===typeof e||(e=Error(a,b,c),e.columnNumber=f,e.stack=b||c||f?p(ja,e.message,"at "+p(":",b,c,f)):D);var d=n.pop()||{};e.attribution=p(":",e.attribution||d.attribution,d.name);e.logLevel=d.logLevel;e.attribution&&console&&console.log&&console.log([e.logLevel||"ERROR",a,"thrown by",e.attribution].join(" "));n=[];W&&(d=[].slice.call(arguments),
d[4]=e,W.apply(g,d))};B.prototype={logError:function(a,b,c,f){b={message:b,logLevel:c||"ERROR",attribution:p(":",this.attribution,f)};if(g.ueLogError)return g.ueLogError(a||b,a?b:null),!0;console&&console.error&&(console.log(b),console.error(a));return!1},error:function(a,b,c,f){a=Error(p(":",f,a,c));a.attribution=p(":",this.attribution,b);throw a;},guardError:J(),guardFatal:J("FATAL"),guardCurrent:function(a){var b=n[n.length-1];return b?J(b.logLevel,b).call(this,a):a},guardTime:function(a){var b=
n[n.length-1],c=b&&b.name;return c&&c in w?function(){var b=r(),e=a.apply(this,arguments);w[c].async=(w[c].async||0)+r()-b;return e}:a},log:function(a,b,c){return this.logError(null,a,b,c)},declare:v([],!0,!0,!0),register:v([],!0),execute:v([]),AUI_BUILD_DATE:"3.25.5-2025-08-15",when:S(),now:S(!0),trigger:function(a,b,c){var f=t();this.declare(a,{data:b,pageElapsedTime:f-(g.aPageStart||NaN),triggerTime:f});c&&c.instrument&&X.when("prv:a-logTrigger").execute(function(b){b(a)})},handleTriggers:function(){this.log("handleTriggers deprecated")},
attributeErrors:function(a){return new B(a)},_namespace:function(a,b){return new B(a,b)},setPriority:function(a){V?V=!1:this.log("setPriority only accept the first call.")}};var k=y(g,"AmazonUIPageJS",new B);var X=k._namespace("PageJS","AmazonUI");X.declare("prv:p-debug",w);k.declare("p-recorder-events",[]);k.declare("p-recorder-stop",function(){});y(g,"P",k);T();if(h.addEventListener){var Y;h.addEventListener("DOMContentLoaded",Y=function(){k.trigger("a-domready");h.removeEventListener("DOMContentLoaded",
Y,!1)},!1)}var Z=h.documentElement,ka=g._pd(k,L,x,M,Z,U,N,q,"3.25.5-2025-08-15");L(/UCBrowser/i)||ka.localStorage&&M(Z,U.getItem("a-font-class"));k.declare("a-event-revised-handling",!1);k.declare("a-fix-event-off",!1);q("pagejs:pkgExecTime",r()-fa)})(window,document,Date);(function(d,F,H,I){function r(f){h&&h.tag&&h.tag(g(":","aui",f))}function e(f,d){h&&h.count&&h.count("aui:"+f,0===d?0:d||(h.count("aui:"+f)||0)+1)}function t(d){try{return d.test(navigator.userAgent)}catch(y){return!1}}function k(d){return"function"===typeof d}function w(d,g,e){d.addEventListener?d.addEventListener(g,e,!1):d.attachEvent&&d.attachEvent("on"+g,e)}function g(d,e,k,h){e=e&&k?e+d+k:e||k;return h?g(d,e,h):e}"use strict";var h=d.ue,A=String.fromCharCode(92);P.execute("RetailPageServiceWorker",
function(){function f(a,b){l.controller&&a?(a={feature:"retail_service_worker_messaging",command:a},b&&(a.data=b),l.controller.postMessage(a)):a&&e("sw:sw_message_no_ctrl",1)}function y(a){var b=a.data;if(b&&"retail_service_worker_messaging"===b.feature&&b.command&&b.data){var c=b.data;a=d.ue;var m=d.ueLogError;switch(b.command){case "log_counter":a&&k(a.count)&&c.name&&a.count(c.name,0===c.value?0:c.value||1);break;case "log_tag":a&&k(a.tag)&&c.tag&&(a.tag(c.tag),b=d.uex,a.isl&&k(b)&&b("at"));break;
case "log_error":m&&k(m)&&c.message&&m({message:c.message,logLevel:c.level||"ERROR",attribution:c.attribution||"RetailServiceWorker"});break;case "log_weblab_trigger":if(!c.weblab||!c.treatment)break;a&&k(a.trigger)?a.trigger(c.weblab,c.treatment):(e("sw:wt:miss"),e("sw:wt:miss:"+c.weblab+":"+c.treatment));break;default:e("sw:unsupported_message_command",1)}}}function v(a,b){return"sw:"+(b||"")+":"+a+":"}function z(a,b){try{l.register("/service-worker.js").then(function(){e(a+"success")}).catch(function(c){B(c,
a,b)})}catch(c){B(c,a,b)}}function B(a,b,c){var d=a&&"object"===typeof a&&"string"===typeof a.stack?-1!==a.stack.indexOf("webpack://@import/chromium-server/"):!1;d?e(b+"error:suppressed"):(P.logError(a,"[AUI SW] Failed to "+c+" service worker: ","ERROR","RetailPageServiceWorker"),e(b+"failure"))}function C(){n.forEach(function(a){r(a)})}function q(a){return a.capabilities.isAmazonApp&&a.capabilities.android}function D(a,b,c){if(b)if(b.mshop&&q(a))a=v(c,"mshop_and"),b=b.mshop.action,n.push(a+"supported"),
b(a,c);else if(b.browser){a=t(/Chrome/i)&&!t(/Edge/i)&&!t(/OPR/i)&&!a.capabilities.isAmazonApp&&!t(new RegExp(A+"bwv"+A+"b"));var d=b.browser;b=v(c,"browser");a?(a=d.action,n.push(b+"supported"),a(b,c)):n.push(b+"unsupported")}}function E(a,b,c){a&&n.push(v("register",c)+"unsupported");b&&n.push(v("unregister",c)+"unsupported");C()}try{var l=navigator.serviceWorker}catch(a){r("sw:nav_err")}(function(){if(l){var a=function(){f("page_loaded",{rid:d.ue_id,mid:d.ue_mid,pty:d.ue_pty,sid:d.ue_sid,spty:d.ue_spty,
furl:d.ue_furl})};w(l,"message",y);f("client_messaging_ready");P.when("load").execute(a);w(l,"controllerchange",function(){f("client_messaging_ready");"complete"===F.readyState&&a()})}})();var n=[],p=function(a,b){var c=d.uex,m=d.uet;a=g(":","aui","sw",a);"ld"===b&&k(c)?c("ld",a,{wb:1}):k(m)&&m(b,a,{wb:1})},G=function(a,b,c){function m(a){b&&k(b.failure)&&b.failure(a)}function h(){n=setTimeout(function(){r(g(":","sw:"+f,u.TIMED_OUT));m({ok:!1,statusCode:u.TIMED_OUT,done:!1});p(f,"ld")},c||4E3)}var u=
{NO_CONTROLLER:"no_ctrl",TIMED_OUT:"timed_out",UNSUPPORTED_BROWSER:"unsupported_browser",UNEXPECTED_RESPONSE:"unexpected_response"},f=g(":",a.feature,a.command),n,q=!0;if("MessageChannel"in d&&l&&"controller"in l)if(l.controller){var t=new MessageChannel;t.port1.onmessage=function(c){(c=c.data)&&c.feature===a.feature&&c.command===a.command?(q&&(p(f,"cf"),q=!1),p(f,"af"),clearTimeout(n),c.done||h(),c.ok?b&&k(b.success)&&b.success(c):m(c),c.done&&p(f,"ld")):e(g(":","sw:"+f,u.UNEXPECTED_RESPONSE),1)};
h();p(f,"bb");l.controller.postMessage(a,[t.port2])}else r(g(":","sw:"+a.feature,u.NO_CONTROLLER)),m({ok:!1,statusCode:u.NO_CONTROLLER,done:!0});else r(g(":","sw:"+a.feature,u.UNSUPPORTED_BROWSER)),m({ok:!1,statusCode:u.UNSUPPORTED_BROWSER,done:!0})};(function(){l?(p("ctrl_changed","bb"),l.addEventListener("controllerchange",function(){r("sw:ctrl_changed");p("ctrl_changed","ld")})):e(g(":","sw:ctrl_changed","sw_unsupp"),1)})();(function(){var a=function(){p(b,"ld");var a=d.uex;G({feature:"page_proxy",
command:"request_feature_tags"},{success:function(b){b=b.data;Array.isArray(b)&&b.forEach(function(a){"string"===typeof a?r(g(":","sw:ppft",a)):e(g(":","sw:ppft","invalid_tag"),1)});e(g(":","sw:ppft","success"),1);h&&h.isl&&k(a)&&a("at")},failure:function(a){e(g(":","sw:ppft","error:"+(a.statusCode||"ppft_error")),1)}})};if("requestIdleCallback"in d){var b=g(":","ppft","callback_ricb");d.requestIdleCallback(a,{timeout:1E3})}else b=g(":","ppft","callback_timeout"),setTimeout(a,0);p(b,"bb")})();var x=
{reg:{},unreg:{}};x.reg.mshop={action:z};x.reg.browser={action:z};(function(a){var b=a.reg,c=a.unreg;l&&l.getRegistrations?(P.when("A").execute(function(b){if((a.reg.mshop||a.unreg.mshop)&&"function"===typeof q&&q(b)){var g=a.reg.mshop?"T1":"C",f=d.ue;f&&f.trigger?f.trigger("MSHOP_SW_CLIENT_446196",g):e("sw:mshop:wt:failed")}D(b,c,"unregister")}),w(d,"load",function(){P.when("A").execute(function(a){D(a,b,"register");C()})})):(E(b&&b.browser,c&&c.browser,"browser"),P.when("A").execute(function(a){"function"===
typeof q&&q(a)&&E(b&&b.mshop,c&&c.mshop,"mshop_and")}))})(x)})})(window,document,Date);
'use strict';(function(b){function q(a,e,d){function g(a,b,c){var f=Array(e.length);~l&&(f[l]={});~m&&(f[m]=c);for(c=0;c<n.length;c++){var g=n[c],h=a[c];f[g]=h}for(c=0;c<p.length;c++)g=p[c],h=b[c],f[g]=h;a=d.apply(null,f);return~l?f[l]:a}"string"!==typeof a&&b.P.error("C001");-1===a.indexOf("@")&&-1<a.indexOf("/")&&(-1<a.indexOf("es3")||-1<a.indexOf("evergreen"))&&(a=a.substring(0,a.lastIndexOf("/")));if(!r[a]){r[a]=!0;d||(d=e,e=[]);a=a.split(":",2);var c=a[1]?a[0]:void 0,f=(a[1]||a[0]).replace(/@capability\//,
"@c/"),k=c?b.P._namespace(c):b.P,t=!f.lastIndexOf("@c/",0),u=!f.lastIndexOf("@m/",0),n=[];a=[];var p=[],v=[],m=-1,l=-1;for(c=0;c<e.length;c++){var h=e[c];"module"===h&&k.error("C002");"exports"===h?l=c:"require"===h?m=c:h.lastIndexOf("@p/",0)?h.lastIndexOf("@c/",0)&&h.lastIndexOf("@m/",0)?(n.push(c),a.push("mix:"+h)):(p.push(c),v.push(h)):(n.push(c),a.push(h.substr(3)))}k.when.apply(k,a).register("mix:"+f,function(){var a=[].slice.call(arguments);return t||u||~m||p.length?{capabilities:v,cardModuleFactory:function(b,
c){b=g(a,b,c);b.P=k;return b},require:~m?q:void 0}:g(a,[],function(){})});(t||u)&&k.when("mix:@amzn/mix.client-runtime","mix:"+f).execute(function(a,b){a.registerCapabilityModule(f,b)});k.when("mix:"+f).register("xcp:"+f,function(a){return a});var q=function(a,b,c){try{var e=-1<f.indexOf("/")?f.split("/")[0]:f,d=a[0],g=d.lastIndexOf("./",0)?d:e+"/"+d.substr(2),h=g.lastIndexOf("@p/",0)?"mix:"+g:g.substr(3);k.when(h).execute(function(a){try{b(a)}catch(x){c(x)}})}catch(w){c(w)}}}}"use strict";var r=
{};b.mix_d||((b.Promise?P:P.when("3p-promise")).register("@p/promise-is-ready",function(a){b.Promise=b.Promise||a}),(Array.prototype.includes?P:P.when("a-polyfill")).register("@p/polyfill-is-ready",function(){}),b.mix_d=function(a,b,d){P.when("@p/promise-is-ready","@p/polyfill-is-ready").execute("@p/mix-d-deps",function(){q(a,b,d)})},b.xcp_d=b.mix_d,P.when("mix:@amzn/mix.client-runtime").execute(function(a){P.declare("xcp:@xcp/runtime",a)}));b.mixTimeout||(b.mixTimeout=function(a,e,d){b.mixCardInitTimeouts||
(b.mixCardInitTimeouts={});b.mixCardInitTimeouts[e]&&clearTimeout(b.mixCardInitTimeouts[e]);b.mixCardInitTimeouts[e]=setTimeout(function(){P.log("Client-side initialization timeout","WARN",a)},d)});b.mix_csa_map=b.mix_csa_map||{};b.mix_csa_internal=b.mix_csa_internal||function(a,e,d){return b.mix_csa_map[e]=b.mix_csa_map[e]||b.csa(a,d)};b.mix_csa_internal_key=b.mix_csa_internal_key||function(a,b){for(var d="",e=0;e<b.length;e++){var c=b[e];void 0!==a[c]&&"object"!==typeof a[c]&&(d+=c+":"+a[c]+",")}if(!d)throw Error("bad mix-csa key gen.");
return d};b.mix_csa_event=b.mix_csa_event||function(a){try{var e=b.mix_csa_internal_key(a,["producerId"])}catch(d){return P.logError(d,"MIX C005","WARN",void 0),function(){}}try{return b.mix_csa_internal("Events",e,a)}catch(d){return P.logError(d,"MIX C004","WARN",e),function(){}}};b.mix_csa=b.mix_csa||function(a,e){try{e=e||"";var d=document.querySelectorAll(a);if(1<d.length)for(var g=0;g<d.length;g++){if(d[g].querySelector(e)){var c=d[g];break}}else 1===d.length&&(c=d[0]);if(!c)throw Error(" ");

In [5]:
# Mobiles info
Mobile_info=[]
Mob= Soup.find_all("div", class_="_cDEzb_p13n-sc-css-line-clamp-3_g3dy1")

for i in Mob:
    Mobile_info.append((i.text).strip() )

print(Mobile_info)

['iQOO Z10x 5G (Ultramarine, 6GB RAM, 128GB Storage) | 6500 mAh Large Capacity Battery | Dimensity 7300 Processor | Military-Grade Durability', 'iQOO Z10x 5G (Titanium, 6GB RAM, 128GB Storage) | 6500 mAh Large Capacity Battery | Dimensity 7300 Processor | Military-Grade Durability', 'iQOO Z10R 5G (Aquamarine, 8GB RAM, 128GB Storage) | 32MP 4K Selfie Camera | Quad-Curved AMOLED Display | Dimensity 7400 Processor with 750K+ AnTuTu', 'iQOO Z10x 5G (Ultramarine, 8GB RAM, 128GB Storage) | 6500 mAh Large Capacity Battery | Dimensity 7300 Processor | Military-Grade Durability', 'iQOO Z10x 5G (Titanium, 8GB RAM, 128GB Storage) | 6500 mAh Large Capacity Battery | Dimensity 7300 Processor | Military-Grade Durability', 'Redmi A4 5G (Starry Black, 6GB RAM, 128GB Storage) | Global Debut SD 4s Gen 2 | Segment Largest 6.88in 120Hz | 50MP Dual Camera | 18W Fast Charging', 'Redmi A4 5G (Sparkle Purple, 6GB RAM, 128GB Storage) | Global Debut SD 4s Gen 2 | Segment Largest 6.88in 120Hz | 50MP Dual Camera | 18W Fast Charging', 'iQOO Z10 Lite 5G (Cyber Green, 6GB RAM, 128GB Storage) | 6000 mAh Battery | Dimensity 6300 5G Processor with 433K+* AnTuTu Score | IP64 Rated & Military Grade Shock-Resistance*', 'iQOO Z10 Lite 5G (Titanium Blue, 6GB RAM, 128GB Storage) | 6000 mAh Battery | Dimensity 6300 5G Processor with 433K+* AnTuTu Score | IP64 Rated & Military Grade Shock-Resistance*', 'iQOO Z10R 5G (Moonstone, 8GB RAM, 128GB Storage) | 32MP 4K Selfie Camera | Quad-Curved AMOLED Display | Dimensity 7400 Processor with 750K+ AnTuTu', 'realme NARZO 80 Lite 5G (Crystal Purple, 6GB+128GB) | 6000mAh Long-Lasting Battery | MediaTek Dimensity 6300 5G | AI Assist | IP64 Rated Water & Dust Resistance | Military-Grade Durability', 'realme NARZO 80 Lite 5G (Onyx Black, 6GB+128GB) | 6000mAh Long-Lasting Battery | MediaTek Dimensity 6300 5G | AI Assist | IP64 Rated Water & Dust Resistance | Military-Grade Durability', "realme NARZO 80 Lite 4G (Beach Gold, 4GB+64GB) | 6300mAh Segment's Biggest Battery | 7.94mm Slim Design | 300% Ultra Volume | Pulse Light: 9 Colors, 5 Glow Modes | Ai Assist", 'OnePlus Nord CE5 | Massive 7100mAh Battery | MediaTek Dimensity 8350 Apex | Powered by OnePlus AI | 8GB + 128GB | Black Infinity', 'iQOO Z10 Lite 5G (Cyber Green, 8GB RAM, 256GB Storage) | 6000 mAh Battery | Dimensity 6300 5G Processor with 433K+* AnTuTu Score | IP64 Rated & Military Grade Shock-Resistance*', 'iQOO Z10R 5G (Aquamarine, 8GB RAM, 256GB Storage) | 32MP 4K Selfie Camera | Quad-Curved AMOLED Display | Dimensity 7400 Processor with 750K+ AnTuTu', 'iQOO Z10 Lite 5G (Titanium Blue, 8GB RAM, 256GB Storage) | 6000 mAh Battery | Dimensity 6300 5G Processor with 433K+* AnTuTu Score | IP64 Rated & Military Grade Shock-Resistance*', 'OnePlus Nord 5 | Snapdragon 8s Gen 3 | Stable 144FPS Gaming | Dual 50MP Flagship Camera | Powered by OnePlus AI | 8GB + 256GB | Phantom Grey', 'iQOO Z10 Lite 5G (Cyber Green, 4GB RAM, 128GB Storage) | 6000 mAh Battery | Dimensity 6300 5G Processor with 433K+* AnTuTu Score | IP64 Rated & Military Grade Shock-Resistance*', 'OnePlus Nord CE5 | Massive 7100mAh Battery | MediaTek Dimensity 8350 Apex | Powered by OnePlus AI | 8GB + 256GB | Nexus Blue', 'OnePlus Nord 5 | Snapdragon 8s Gen 3 | Stable 144FPS Gaming | Dual 50MP Flagship Camera | Powered by OnePlus AI | 8GB + 256GB | Dry Ice', 'OnePlus Nord CE5 | Massive 7100mAh Battery | MediaTek Dimensity 8350 Apex | Powered by OnePlus AI | 8GB + 256GB | Black Infinity', 'iQOO Z10 Lite 5G (Titanium Blue, 4GB RAM, 128GB Storage) | 6000 mAh Battery | Dimensity 6300 5G Processor with 433K+* AnTuTu Score | IP64 Rated & Military Grade Shock-Resistance*', 'OnePlus Nord CE5 | Massive 7100mAh Battery | MediaTek Dimensity 8350 Apex | Powered by OnePlus AI | 8GB + 128GB | Nexus Blue', 'iQOO Z10x 5G (Ultramarine, 8GB RAM, 256GB Storage) | 6500 mAh Large Capacity Battery | Dimensity 7300 Processor | Military-Grade Durability', 'OnePlus Nord 5 | Snapdragon 8s Gen 3 | Stable 144FPS Gaming | Dual 50MP Flagship Camera | Powered by OnePlus AI | 8GB + 256GB | Marble Sands', "iQOO Z10 5G (Glacier Silver, 8GB RAM, 256GB Storage) | India's Biggest Ever 7300 mAh Battery | Snapdragon 7s Gen 3 Processor | Brightest Quad Curved AMOLED Display in The Segment", "realme NARZO 80 Lite 4G (Beach Gold, 6GB+128GB) | 6300mAh Segment's Biggest Battery | 7.94mm Slim Design | 300% Ultra Volume | Pulse Light: 9 Colors, 5 Glow Modes | Ai Assist", 'iQOO Neo 10 (Titanium Chrome, 8GB RAM, 256GB Storage) | Snapdragon 8s Gen 4 Processor & SuperComputing Chip Q1 | 7000 mAh Battery | Segment’s Highest 144 FPS Gaming Smartphone', "realme NARZO 80 Lite 4G (Obsidian Black, 4GB+64GB) | 6300mAh Segment's Biggest Battery | 7.94mm Slim Design | 300% Ultra Volume | Pulse Light: 9 Colors, 5 Glow Modes | Ai Assist", 'OnePlus Nord CE5 | Massive 7100mAh Battery | MediaTek Dimensity 8350 Apex | Powered by OnePlus AI | 12GB + 256GB | Black Infinity', "iQOO Z10 5G (Silver, 8GB RAM, 128GB Stroage) | India's Biggest Ever 7300 mAh Battery | Snapdragon 7s Gen 3 Processor | Brightest Quad Curved AMOLED Display in The Segment", 'iQOO Neo 10 (Titanium Chrome, 12GB RAM, 256GB Storage) | Snapdragon 8s Gen 4 Processor & SuperComputing Chip Q1 | 7000 mAh Battery | Segment’s Highest 144 FPS Gaming Smartphone', 'Samsung Galaxy M36 5G (Velvet Black, 6 GB RAM, 128 GB Storage)| Circle to Search| Google Gemini| Corning Gorilla Glass Victus+| 7.7mm Slim| AI Enhanced 50 MP OIS Triple Camera| Unmatched Nightography', 'Lava Bold N1 Pro (Titanium Gold, 4 GB RAM, 128 GB Storage)| Bigger 6.67" HD+ IP54 Display | 120 Hz Refresh Rate | 50 MP AI Triple Rear Camera | 8 MP Front Camera| 5000 mAh Battery | Charger in Box', 'iQOO Z10x 5G (Titanium, 8GB RAM, 256GB Storage) | 6500 mAh Large Capacity Battery | Dimensity 7300 Processor | Military-Grade Durability', 'realme NARZO 80x 5G (Deep Ocean,6GB+128GB) | Dimensity 6400 5G Chipset | 6000mAh Long-Lasting Battery | 45W Fast Charge | 120Hz Eye Comfort Display | IP69 Top-Tier Waterproof', 'Samsung Galaxy M36 5G (Serene Green, 6 GB RAM, 128 GB Storage)| Circle to Search| Google Gemini| Corning Gorilla Glass Victus+| 7.7mm Slim| AI Enhanced 50 MP OIS Triple Camera| Unmatched Nightography', 'OnePlus Nord CE5 | Massive 7100mAh Battery | MediaTek Dimensity 8350 Apex | Powered by OnePlus AI | 8GB + 256GB | Marble Mist', 'CMF Phone 2 Pro (Light Green, 8GB RAM, 128GB Storage)', 'OnePlus Nord CE5 | Massive 7100mAh Battery | MediaTek Dimensity 8350 Apex | Powered by OnePlus AI | 8GB + 128GB | Marble Mist', "iQOO Z10 5G (Stellar Black, 8GB RAM, 128GB Storage) | India's Biggest Ever 7300 mAh Battery | Snapdragon 7s Gen 3 Processor | Brightest Quad Curved AMOLED Display in The Segment", 'Lava Bold N1 Pro (Stealth Black, 4 GB RAM, 128 GB Storage)| Bigger 6.67" HD+ IP54 Display | 120 Hz Refresh Rate | 50 MP AI Triple Rear Camera | 8 MP Front Camera| 5000 mAh Battery| Charger in Box', "iQOO Z10 5G (Stellar Black, 8GB RAM, 256GB Storage) | India's Biggest Ever 7300 mAh Battery | Snapdragon 7s Gen 3 Processor | Brightest Quad Curved AMOLED Display in The Segment", 'iQOO Neo 10 (Inferno Red, 8GB RAM, 256GB Storage) | Snapdragon 8s Gen 4 Processor & SuperComputing Chip Q1 | 7000 mAh Battery | Segment’s Highest 144 FPS Gaming Smartphone', "iQOO Z10 5G (Glacier Silver, 12GB RAM, 256GB Storage) | India's Biggest Ever 7300 mAh Battery | Snapdragon 7s Gen 3 Processor | Brightest Quad Curved AMOLED Display in The Segment", 'realme NARZO 80x 5G (Sunlit Gold,6GB+128GB) | Dimensity 6400 5G Chipset | 6000mAh Long-Lasting Battery | 45W Fast Charge | 120Hz Eye Comfort Display | IP69 Top-Tier Waterproof', 'OnePlus Nord 5 | Snapdragon 8s Gen 3 | Stable 144FPS Gaming | Dual 50MP Flagship Camera | Powered by OnePlus AI | 12GB + 256GB | Dry Ice', 'Samsung Galaxy M36 5G (Velvet Black, 8 GB RAM, 128 GB Storage)| Circle to Search| Google Gemini| Corning Gorilla Glass Victus+| 7.7mm Slim| AI Enhanced 50 MP OIS Triple Camera| Unmatched Nightography', 'iQOO Z10R 5G (Moonstone, 8GB RAM, 256GB Storage) | 32MP 4K Selfie Camera | Quad-Curved AMOLED Display | Dimensity 7400 Processor with 750K+ AnTuTu']

In [6]:
# ratings
Ratings=[]
R= Soup.find_all("div", class_="a-icon-row")

for i in R:
    Ratings.append((i.text).strip() )

print(Ratings)

['4.3 out of 5 stars\u20093,248', '4.3 out of 5 stars\u20093,248', '4.2 out of 5 stars\u2009178', '4.3 out of 5 stars\u20093,248', '4.3 out of 5 stars\u20093,248', '3.9 out of 5 stars\u20095,789', '3.9 out of 5 stars\u20095,789', '4.0 out of 5 stars\u20091,313', '4.0 out of 5 stars\u20091,313', '4.2 out of 5 stars\u2009178', '4.2 out of 5 stars\u2009555', '4.2 out of 5 stars\u2009555', '4.4 out of 5 stars\u2009125', '4.4 out of 5 stars\u2009855', '4.0 out of 5 stars\u20091,313', '4.2 out of 5 stars\u2009178', '4.0 out of 5 stars\u20091,313', '4.4 out of 5 stars\u2009897', '4.0 out of 5 stars\u20091,313', '4.4 out of 5 stars\u2009855', '4.4 out of 5 stars\u2009897', '4.4 out of 5 stars\u2009855', '4.0 out of 5 stars\u20091,313', '4.4 out of 5 stars\u2009855', '4.3 out of 5 stars\u20093,248', '4.4 out of 5 stars\u2009897', '4.3 out of 5 stars\u20091,953', '4.4 out of 5 stars\u2009125', '4.3 out of 5 stars\u20091,665', '4.4 out of 5 stars\u2009125', '4.4 out of 5 stars\u2009855', '4.3 out of 5 stars\u20091,953', '4.3 out of 5 stars\u20091,665', '3.8 out of 5 stars\u2009918', '3.9 out of 5 stars\u2009448', '4.3 out of 5 stars\u20093,248', '4.1 out of 5 stars\u20091,084', '3.8 out of 5 stars\u2009918', '4.4 out of 5 stars\u2009855', '4.4 out of 5 stars\u200974', '4.4 out of 5 stars\u2009855', '4.3 out of 5 stars\u20091,953', '3.9 out of 5 stars\u2009448', '4.3 out of 5 stars\u20091,953', '4.3 out of 5 stars\u20091,665', '4.3 out of 5 stars\u20091,953', '4.1 out of 5 stars\u20091,084', '4.4 out of 5 stars\u2009897', '3.8 out of 5 stars\u2009918', '4.2 out of 5 stars\u2009178']

In [27]:
Serial = []
Mobile_info = []
Ratings = []
Price = []

for page in range(1, 11):
    url = f"https://www.amazon.in/gp/new-releases/electronics/1805560031/ref=zg_bsnr_pg_2_electronics?ie=UTF8&pg={page}"
    headers = {
        "User-Agent": "Mozilla/5.0"
    }
    response = requests.get(url, headers=headers)
   Mobile_info=[]
    Mob= Soup.find_all("div", class_="_cDEzb_p13n-sc-css-line-clamp-3_g3dy1")

        for i in Mob:
            Mobile_info.append((i.text).strip() )

            print(Mobile_info)

        for i in range(min(len(Mob), len(R), len(P))):
            Serial.append(len(Serial) + 1)
            Mobile_info.append(Mob[i].text.strip())
            Ratings.append(R[i].text.strip())
            #Price.append(P[i].text.strip())

In [28]:
df = pd.DataFrame({
    "Serial": Serial,
    "Mobile Info": Mobile_info,
    "Ratings": Ratings,
    "Price": Price
})

In [29]:
print(df)

Empty DataFrame
Columns: [Serial, Mobile Info, Ratings, Price]
Index: []

In [30]:
df

Empty DataFrame
Columns: [Serial, Mobile Info, Ratings, Price]
Index: []

In [15]:
df["Price"] = df["Price"].str.replace("₹", "", regex=False) \
                         .str.replace(",", "", regex=False) \
                         .astype(float)

NameError: name 'df' is not defined

In [32]:
df

,Mobile,Rating,Price in ₹
0,"iQOO Z10 Lite 5G (Titanium Blue, 6GB RAM, 128G...","4.0 out of 5 stars 1,183",18999.0
1,"iQOO Z10x 5G (Ultramarine, 6GB RAM, 128GB Stor...","4.3 out of 5 stars 3,062",18999.0
2,"iQOO Z10 Lite 5G (Cyber Green, 6GB RAM, 128GB ...","4.0 out of 5 stars 1,183",18999.0
3,"iQOO Z10 Lite 5G (Titanium Blue, 4GB RAM, 128G...","4.0 out of 5 stars 1,183",18999.0
4,"iQOO Z10x 5G (Titanium, 6GB RAM, 128GB Storage...","4.3 out of 5 stars 3,062",18999.0
...,...,...,...
495,"POCO C71, Desert Gold (6GB, 128GB)",4.2 out of 5 stars 61,18999.0
496,"realme NARZO 80x 5G (Sunlit Gold,6GB+128GB) | ...","4.1 out of 5 stars 1,028",18999.0
497,"iQOO Z10R 5G (Aquamarine, 12GB RAM, 256GB Stor...",4.2 out of 5 stars 87,18999.0
498,OnePlus Nord 5 | Snapdragon 8s Gen 3 | Stable ...,4.4 out of 5 stars 776,18999.0
499,"Samsung Galaxy M36 5G (Velvet Black, 8 GB RAM,...",3.8 out of 5 stars 847,18999.0

In [35]:
df["Rating"] = df["Rating"].str.split("out of 5 stars", n=1, expand=True)[0].str.strip()

In [36]:
df

                                                Mobile Rating  Price in ₹
0    iQOO Z10 Lite 5G (Titanium Blue, 6GB RAM, 128G...    4.0     18999.0
1    iQOO Z10x 5G (Ultramarine, 6GB RAM, 128GB Stor...    4.3     18999.0
2    iQOO Z10 Lite 5G (Cyber Green, 6GB RAM, 128GB ...    4.0     18999.0
3    iQOO Z10 Lite 5G (Titanium Blue, 4GB RAM, 128G...    4.0     18999.0
4    iQOO Z10x 5G (Titanium, 6GB RAM, 128GB Storage...    4.3     18999.0
..                                                 ...    ...         ...
495                 POCO C71, Desert Gold (6GB, 128GB)    4.2     18999.0
496  realme NARZO 80x 5G (Sunlit Gold,6GB+128GB) | ...    4.1     18999.0
497  iQOO Z10R 5G (Aquamarine, 12GB RAM, 256GB Stor...    4.2     18999.0
498  OnePlus Nord 5 | Snapdragon 8s Gen 3 | Stable ...    4.4     18999.0
499  Samsung Galaxy M36 5G (Velvet Black, 8 GB RAM,...    3.8     18999.0

[500 rows x 3 columns]

In [23]:
df.to_csv('Mobile_info_13Aug.csv',index=False)

In [ ]:
df[['Model Name', 'Model info']] = df['Mobile'].str.split('|', n=1, expand=True)

In [ ]:
df

In [ ]:
df['Model info']

In [ ]:
df[['Battery ','Processor']] = df['Model info'].str.split('|', n=1, expand=True)

In [ ]:
import pandas as pd
import re

In [ ]:
df1 = pd.read_csv('Mobile_info.csv')

In [ ]:
for i in df1['Model info'] : 
    str1 = (i)
    break

In [ ]:
re.findall('.{} mAh', str1)

In [ ]:
str1

In [ ]:
df['Battery_mAh'] = df['Battery'].str.extract(r'(\d+)\s*mAh').astype(float)
print(df)

In [ ]:
<span class="_cDEzb_p13n-sc-price_3mJ9Z">₹13,498.00</span>